[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FFDF"
authors = [{name = "Cagzie", email = "jack@cagzie.com"}]
dynamic = ["version", "description"]
